-- Create games table for GameTracker
create table if not exists public.games (
  id bigint generated by default as identity primary key,
  title text not null,
  genre text not null,
  rating int4 not null check (rating between 1 and 5),
  created_at timestamptz not null default now()
);

-- Turn on RLS and allow anonymous app access for this project
alter table public.games enable row level security;

drop policy if exists "Allow read games" on public.games;
create policy "Allow read games"
on public.games
for select
to anon
using (true);

drop policy if exists "Allow insert games" on public.games;
create policy "Allow insert games"
on public.games
for insert
to anon
with check (true);

drop policy if exists "Allow delete games" on public.games;
create policy "Allow delete games"
on public.games
for delete
to anon
using (true);
